# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('job_position', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('hours_per_week', models.IntegerField()),
                ('where_found_us', models.CharField(max_length=75)),
                ('country', models.CharField(max_length=75)),
                ('english_level', models.CharField(max_length=75)),
                ('comments', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
