# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_country_englishlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Country'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='english_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.EnglishLevel'),
        ),
    ]
