# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20170105_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='field_name',
        ),
    ]
